# Generated by Django 5.2.5 on 2025-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auteur",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
